### PR TITLE
Reorganising some includes and headers

### PR DESCRIPTION
**Pull request by Rossmaxx**
Resolves: none. just a code cleanup

renamed include/audacity to include/interfaces (cause most of the headers in it have interface in their names. I also moved the Types.h out of the interfaces directory. Also changed the includes appropriately.

- [x] I made sure the code compiles on my machine.
- [ ] I made sure there are no unnecessary changes in the code.
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving.
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?".
- [x] I hereby reaffirm that I am licensing my contribution under the GNU General Public License v2.0 or later (`GPL-2.0-or-later`).

### CODE REVIEW

**Comment by AnErrupTion** [comment]
Workflows are failing.

**Comment by Rossmaxx** [comment]
wait, what's happening? it built fine on my system.

**Comment by Rossmaxx** [comment]
i left out one last save. commited that one. let's see if it builds now

**Comment by Rossmaxx** [comment]
Merged so soon?

**Pull request merged**
